config/routes.rb
HnClone::Application.routes.draw do

  devise_for :users

  root :to => 'articles#index'
  resources :articles
  resources :users, only: [:show]
  resources :votes, only: [:create]
  resources :comments
  resources :banned_users, only: [:create]
  resources :flagged_articles, only: [:create]

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :url
  URL_RULE = /^http/i
  belongs_to :user
  has_many :votes, :as => :voteable
  has_many :comments
  has_one  :flagged_article

  validates :url, :presence => true, :uniqueness => true, :format => { :with => URL_RULE, :message => 'Not a valid URL' }
  validates_presence_of :user_id
  validates :title, :presence => true, :length => { :maximum => 150 }
  def self.non_flagged_articles
    Article.find_by_sql(
      "SELECT * FROM articles WHERE articles.id NOT IN
                (SELECT article_id FROM flagged_articles)")
  end

  def score
    time_in_hours = (Time.now - self.created_at) / 3600
    num_votes = self.votes.length
    gravity = 1.8
    return -(num_votes) / ((time_in_hours + 2) ** gravity)
  end

  def top_level_comments
    self.comments.where(:parent_comment_id => nil).sort_by!(&:score).reverse
  end

  def upvotes
    self.votes.where(:value => 1)
  end

  def too_late_to_edit?
    Time.now - self.created_at > 900
  end

  def flagged?
    self.flagged_article
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :find_article, :only => [:show, :edit, :update]

    def index
        respond_to do |format|
            format.html {
                @articles = Kaminari.paginate_array(Article.non_flagged_articles.sort_by! { |article| article.score }).page(params[:page]).per(20)
            }
            format.json {
                render :json => Article.non_flagged_articles.sort_by! { |article| article.score }
            }
        end
    end
    #testing comment
    def show
        @comment = @article.comments.new
    end

    def new
        @article = Article.new
        unless signed_in?
            flash[:error] = 'Please sign in to submit an article'
            redirect_to new_user_session_path
        end
    end

    def create
        @article = Article.new(params[:article])
        @article[:user_id] = current_user.id
        if @article.save
            flash[:success] = "Thanks for submitting an article"
            @article.votes.create(:user_id => current_user.id, :value => 1)
            redirect_to root_path
        else
            flash[:error] = "Invalid Submission"
            render 'new'
        end
    end

    def edit
        if current_user != @article.user
            flash[:error] = "That article doesn't belong to you!"
            redirect_to root_path
        end
        if @article.too_late_to_edit?
            flash[:error] = "Can't edit after 15 minutes"
            redirect_to root_path
        end
    end

  def update
    if current_user == @article.user && @article.update_attributes(params[:article])
      flash[:success] = 'Article successfully updated'
      redirect_to user_path(current_user)
    else
      flash[:error] = "Invalid Edit"
      redirect_to edit_article_path(@article)
    end
  end

  private

  def find_article
    @article = Article.find_by_id(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1><br>
<%= form_for @article do |f| %>
  <p>
    <%= f.label 'Title' %>
    <%= f.text_field :title %><br />
  </p>
  <p>
    <%= f.label :field_name, "URL" %>
    <%= f.text_field :url %><br />
  </p>
  <%= f.submit class: "btn btn-large btn-success" %>
<% end %>

app/views/articles/index.html.erb
<table width="100%">
<% @articles.each do |article| %>
  <tr>
    <td><%= link_to(article.title, article.url) %><p><em>posted by</em> 
     <%= link_to(article.user.name, user_path(article.user)) %> <%= time_ago_in_words(article.created_at) %> ago | 
        <%= pluralize(article.votes.length, 'point') %> | 
    <% if signed_in? %>
      <% if Vote.find_by_voteable_id_and_voteable_type_and_user_id(article.id, 'Article', current_user.id) %>
        Upvoted | 
      <% else %>
        <%= link_to('Upvote!', votes_path( :vote => {:voteable_id => article.id, :voteable_type => 'Article', :value => 1}), :method => :post) %> |
      <% end %>
    <% end %>
    <%= link_to(pluralize(article.comments.length, 'comment'), article_path(article)) %>
    <% if signed_in? && current_user.admin? %>
       | <%= link_to 'Flag Article', flagged_articles_path(:flagged_article => {:article_id => article.id}), :method => 'POST' %></p></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>Submit New Article</h1><br>
<%= form_for @article do |f| %>
  <p>
    <%= f.label 'Title' %>
    <%= f.text_field :title %><br />
  </p>
  <p>
    <%= f.label :field_name, "URL" %>
    <%= f.text_field :url %><br />
  </p>
  <%= f.submit class: "btn btn-large btn-success" %>
<% end %>

app/views/articles/show.html.erb
<h1><%= link_to(@article.title, @article.url ) %></h1>
<p><em>posted by</em> <%= link_to(@article.user.name, user_path(@article.user)) %> <%= time_ago_in_words(@article.created_at) %> ago</p><br />

<% if signed_in? %>
    <%= form_for @comment, :remote => true do |f| %>
      <p>
        <%= f.text_area :body, style: "height:100px; width: 500px;"%><br />
      </p>
      <%= f.hidden_field :article_id, :value => @comment.article_id %><br />

      <%= f.submit class: "btn btn-large btn-success"%>
    <% end %>
<% end %>

<ul class="top-level comments">
<%= render :partial => 'common/comment', :collection => @article.top_level_comments %>
</ul>