config/routes.rb
HnClone::Application.routes.draw do

  devise_for :users

  root :to => 'articles#index'
  resources :articles
  resources :users, only: [:show]
  resources :votes, only: [:create]
  resources :comments
  resources :banned_users, only: [:create]
  resources :flagged_articles, only: [:create]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable

  validates_presence_of :name
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :is_admin, :password, :password_confirmation, :remember_me
  has_many :articles
  has_many :comments
  has_one  :banned_user

  def karma
    self.articles.inject(0) { |count, article| count + article.upvotes.length } +
    self.comments.inject(0) { |count, comment| count + comment.upvotes.length }
  end

  def can_downvote?
    karma >= 100
  end

  def admin?
    self.is_admin
  end

  def banned?
    self.banned_user
  end

  def active_for_authentication?
    super && !self.banned?
  end

  def inactive_message
    !self.banned? ? super : "You've been banned!"
  end


  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_id(params[:id])
    @articles = Article.where(user_id: @user.id).page(params[:page]).per(5)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if signed_in? && current_user.admin? %>
  <% if @user.banned? %>
    <p class="alert alert-error">User Banned!</p>
  <% else %>
    <p>Admin Actions: <%= link_to('BAN USER', banned_users_path(:banned_user => {:user_id => @user.id}), :method => 'POST') %></p>
  <% end %>
<% end %>

<h1><%= @user.name %> : <%= @user.karma %> Karma</h1>

<h3>Submitted articles:</h3>
<table width='100%'>
<% @articles.each do |article| %>
  <tr>
    <td><%= link_to(article.title, article.url) %> - <em><%= time_ago_in_words(article.created_at) %> ago</em></td>
    <td><%= pluralize(article.votes.length,'point') %></td>
    <td><%= link_to(pluralize(article.comments.length, 'comment'), article_path(article)) %></td>
    <td><%= link_to("Edit", edit_article_path(article)) if @user == current_user && !article.too_late_to_edit? %></td>
  </tr>
<% end %>
</table>
<%= paginate @articles %>