config/routes.rb
HnClone::Application.routes.draw do

  devise_for :users

  root :to => 'articles#index'
  resources :articles
  resources :users, only: [:show]
  resources :votes, only: [:create]
  resources :comments
  resources :banned_users, only: [:create]
  resources :flagged_articles, only: [:create]

end

app/views/common/_comment.html.erb
<span id=<%="comment-#{comment.id}"%>>
<li>

<p>
    <strong><%= link_to comment.user.name, user_path(comment.user) %></strong><em> - <%= time_ago_in_words(comment.created_at) %> ago</em> -
    <%= comment.body %>
</p>
<p>
  <%= pluralize(comment.upvotes.length, 'upvote')%> -
  <%= pluralize(comment.downvotes.length, 'downvote')%> -
  <%= link_to('Reply ', comment_path(comment)) %>
  <% if signed_in? %>
     -
    <% if Vote.find_by_voteable_id_and_voteable_type_and_user_id(comment.id, 'Comment', current_user.id) %>
      Voted
    <% else %>
      <%= link_to('Upvote!', votes_path(
        :vote => {:voteable_id => comment.id,
                  :voteable_type => 'Comment',
                  :value => 1}),
        :method => :post,
        :remote => true) %>
      -
      <%= link_to('Downvote!', votes_path(
        :vote => {:voteable_id => comment.id,
                  :voteable_type => 'Comment',
                  :value => -1}),
        :method => :post,
        :remote => true) %>
    <% end %>
  <% end %>
</p>
</li>

<ul class="comments">
  <%= render :partial => 'common/comment', :collection => comment.comments_sorted_by_score.reverse %>
</ul>
</span>